---
- hosts: all
  become: true
  tasks:

  #Creating a temp traefik directory on the host
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /temp/traefik
      state: directory
      mode: '0777'

  #Creating a srv directory on the host
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/gregory/srv/traefik/
      state: directory
      mode: '0777'

  #Creating a the configuration directory on the host
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/gregory/srv/traefik/configurations/
      state: directory
      mode: '0777'

  #Checkout the Traefik Repo
  - name: Git Checkout Traefik
    ansible.builtin.git:
      repo: 'https://github.com/gregoryca/traefik.git'
      dest: /temp/traefik

  #Copy the compose file
  - name: copy Docker Compose files to remote server
    copy:
      src: /temp/traefik/docker-compose.yml
      dest: /home/gregory/srv/traefik/
    loop:
    - docker-compose.yml

  #Copy the static config file
  - name: copy config traefik files to remote server
    copy:
      src: /temp/traefik/configurations/traefik.yml
      dest: /home/gregory/srv/traefik/configurations/traefik.yml
    loop:
    - traefik.yml

  #Copy the dynamic config file
  - name: copy config traefik files to remote server
    copy:
      src: /temp/traefik/configurations/dynamic.yml
      dest: /home/gregory/srv/traefik/configurations/dynamic.yml
    loop:
    - dynamic.yml

  #Deploy compose file
  - name: deploy Docker Compose stack on remote server
    docker_compose:
      project_src: /home/gregory/srv/traefik/
      files:
      - docker-compose.yml
      recreate: always

  #Clean up temp folder after deployment
  - name: Delete content & directory
    file:
      state: absent
      path: /temp/traefik