version: "3.3"

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: always
    command:
      # Enable a http challenge named "production" and "development"
      - "--certificatesresolvers.production.acme.tlschallenge=true"
      - "--certificatesresolvers.development.acme.tlschallenge=true"
      # The email to provide to let's encrypt
      - "--certificatesresolvers.production.acme.email=aquiles.craane@gmail.com"
      # Tell it to use our predefined entrypoint named "web"
      - "--certificatesresolvers.production.acme.tlschallenge.entrypoint=web"
      - "--certificatesresolvers.production.acme.storage=/letsencrypt/acme.json"
      
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "51820:51820"
      - "8080:8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/srv/letsencrypt/:/srv/letsencrypt"
      - "/letsencrypt/:/letsencrypt"
      - "traefik-ssl-certs:/ssl-certs"
      - "./:/etc/traefik/"

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.cloud-migrations.nl`)"
      - "traefik.http.routers.traefik-secure.tls.certresolver=production"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080" #port to the webservice
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=Laliloe4life:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0"

      - com.centurylinklabs.watchtower.enable=true

    networks: 
      - web-secure
      - web

networks: 
  web-secure:
    external: true
  web:
    external: true