version: "3.3"

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik.rproxy:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: always 
      
    ports:
      - "80:80"
      - "443:443"
      - "853:853"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #this is to save my ssl certifcates locally
      - "./traefik-ssl-certs:/ssl-certs"
      #this is for my dynamic config
      - "./configurations/:/configurations"
      #this is for my traefik static config
      - "./configurations/:/etc/traefik/"      

    labels:
      - "traefik.enable=true"
      #this is a domain name i have pointed to my home address via no-ip.
      #you can create a no-ip account, and set it up so you have an dynamic DNS address
      #In your domain you create a new CNAME record for your website
      #After that you point that CNAME record to the dynamic DNS record
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.cloud-migrations.nl`)"
      #This is my certresolved named: production and can be found in my static config
      - "traefik.http.routers.traefik-secure.tls.certresolver=production"
      - "traefik.http.routers.traefik-secure.tls=true"
      #Port to traefik dashboard UI
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080" #port to the webservice
      #I have created a docker network named: web-secure
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      #traefik service
      - "traefik.http.routers.traefik-secure.service=api@internal"
      #Use this only if you have Authelia deployed in your infra, and is reachable via an docker network
      - "traefik.http.routers.traefik-secure.middlewares=authelia-secure@docker"
      
    networks:
      - web-secure
      - web
#persisting of my docker network within this stack
networks: 
  web-secure:
    external: true
  web:
    external: true