version: "3.3"

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik.rproxy:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: always 
      
    ports:
      - "80:80"
      - "443:443"
      - "853:853"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-ssl-certs:/ssl-certs"
      - "./configurations/:/configurations"
      - "./configurations/:/etc/traefik/"      

    networks:
      - web-secure
      - web

networks: 
  web-secure:
    external: true
  web:
    external: true
