version: "3.3"

services:
  #########################
  # Traefik reverse proxy #
  #########################
  traefik.rproxy:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: always
    hostname: traefik.rproxy
    ################################################################################################
    # Exposed ports to the host so traefik container can listen to these ports on the host machine #
    ################################################################################################
    ports:
      - "80:80" # Web
      - "443:443" # Web-Secure
      - "853:853" #DNS over TLS

    ###############################################################
    # All volumes which are mounted locally to the traefik folder #
    ###############################################################
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      ##############################################
      # This is to save my ssl certifcates locally #
      ##############################################
      - "./traefik-ssl-certs:/ssl-certs"
      ######################################
      # mountpoint for traefik access logs #
      ######################################
      - "./logs/:/var/log/traefik/"
      #################################
      # This is for my dynamic config #
      #################################
      - "./configurations/:/configurations"
      ########################################
      # This is for my traefik static config #
      ########################################
      - "./configurations/:/etc/traefik/"

    networks:
      - web-secure

#####################################################
# Persisting of my docker network within this stack #
#####################################################
networks:
  web-secure:
    external: true