version: "3.3"

services:
  #####################
  # Traefik Hub-Agent #
  #####################
  hub-agent:
    image: ghcr.io/traefik/hub-agent-traefik:v1.1.0
    pull_policy: always
    container_name: hub-agent
    restart: "on-failure"
    command:
      - run
      - --hub.token={{token}}
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik.rproxy
      - --traefik.tls.insecure=true
      - --hub.url=https://platform.hub.traefik.io/agent
      - --hub.ui.url=https://hub.traefik.io
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web-secure
    depends_on:
      - traefik.rproxy

  #########################
  # Traefik reverse proxy #
  #########################
  traefik.rproxy:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: always
    hostname: traefik.rproxy
    ################################################################################################
    # Exposed ports to the host so traefik container can listen to these ports on the host machine #
    ################################################################################################
    ports:
      - "80:80" # Web
      - "443:443" # Web-Secure
      - "853:853" #DNS over TLS
    environment:
      - BINDMAN_MANAGER_ADDRESS=bindman.listener
    ###############################################################
    # All volumes which are mounted locally to the traefik folder #
    ###############################################################
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      ##############################################
      # This is to save my ssl certifcates locally #
      ##############################################
      - "./traefik-ssl-certs:/ssl-certs"
      ######################################
      # mountpoint for traefik access logs #
      ######################################
      - "./logs/:/var/log/traefik/"
      #################################
      # This is for my dynamic config #
      #################################
      - "./configurations/:/configurations"
      ########################################
      # This is for my traefik static config #
      ########################################
      - "./configurations/:/etc/traefik/"

    networks:
      - web
      - web-secure
      - monitoring-stack

#####################################################
# Persisting of my docker network within this stack #
#####################################################
networks:
  web-secure:
    external: true
  web:
    external: true
  monitoring-stack:
    external: true
