######################################################
# This is a basic workflow to Deploy a traefik stack #
######################################################
name: Deploy Traefik infra

on:
  push:
    branches: [ "dev", "development" ]
  pull_request:
    branches: [ "master" ]

  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Run playbook
        uses: actions/checkout@v3

      #####################################################################
      # Deploys an ansible script to manage the traefik stack deployment #
      #####################################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Deploy infra
        with:
          ###############################
          # Required, playbook filepath #
          ###############################
          playbook: deployment.yml
          ############################################
          # Optional, directory where playbooks live #
          ############################################
          directory: ./deployments
          ###################
          # SSH private key #
          ###################
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ###########################
          # inventory file contents #
          ###########################
          inventory: |
            [linux]
            server17a ansible_host=${{ secrets.HOST }} ansible_port=${{ secrets.PORT }}
            
            [azure]
            app-srv-01 ansible_host=srv-01.westeurope.cloudapp.azure.com ansible_port=22 

            [linux:vars]
            ansible_user = ${{ secrets.USERNAME }}
            ansible_sudo_pass = ${{ secrets.PASSWORD }}
            
            [azure:vars]
            ansible_user=gregory
            ansible_ssh_pass=laliloe4life_
            ansible_sudo_pass=laliloe4life_
