name: Deploy Traefik
#On push to master branch, start a new Traefik deployment
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    #Steps that the pipeline has defined
    steps:

    #Create temp folder
    - name: Create temp folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} #Host to connect to
        username: ${{ secrets.USERNAME }} #Username to authenticate with
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }} #Private key host you're connecting to
        port: ${{ secrets.PORT }} #Port to connect to
        script: mkdir -p /temp/ #Script that get's executed over ssh

    #Starting the Traefik stack deployment
    - name: Download and execute Deployment file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} #Host to connect to
        username: ${{ secrets.USERNAME }} #Username to authenticate with
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }} #Private key host you're connecting to
        port: ${{ secrets.PORT }} #Port to connect to
        script: cd /temp/ && git clone https://github.com/gregoryca/traefik/deployments/deployment.yml && ansible-playbook deployment.yml #Script that get's executed over ssh