name: Deploy Traefik docker-compose

on:
  push:
    branches: [ Development ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Start Traefik stack
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd /home/${{ secrets.USERNAME }}/srv/traefik/ && docker-compose up -d --force-recreate